logging:
    level:
        org.telosystools.saas : 'WARN'

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: mongodb
            port: 27017
            database: db_general
    thymeleaf:
        mode: XHTML
        cache: true

mongeez:
    migrate:
        true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: myimmo

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    hazelcast:
        debug: false
        stickySession: false
        backupCount: 1
