logging:
    level:
        org.telosystools.saas : 'DEBUG'

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: db_general
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

mongeez:
    migrate:
        true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: myimmo

cache:
    timeToLiveSeconds: 3600
    hazelcast:
        debug: true
        stickySession: false
        backupCount: 1
